AWSTemplateFormatVersion: "2010-09-09-OC"
Parameters:
  AccountId:
    Type: String
    Description: The master account ID for an AWS account.
  ServicePrincipal:
    Type: String
Resources:
  DelegateAdmin:
    Type: Community::Organizations::DelegatedAdmin
    Properties:
      AccountId: !Ref AccountId
      ServicePrincipal: !Ref ServicePrincipal
