AWSTemplateFormatVersion: "2010-09-09-OC"
OrganizationBindings:
  SecurityHubMasterBinding:
  SecurityHubMembersBinding:
Parameters:
  MasterAccountId:
    Type: String
    Description: The master account ID for an AWS account.  
Resources:
  Hub: 
    OrganizationBinding: !Ref SecurityHubMasterBinding
    Type: AWS::SecurityHub::Hub
  Members:
    Type: Community::SecurityHub::Members
    OrganizationBinding: !Ref SecurityHubMasterBinding
    DependsOn: Hub
    Properties:
        MemberAccountIDs: Fn::EnumTargetAccounts SecurityHubMembersBinding '${account}'         
  Master:
    Type: Community::SecurityHub::Master
    OrganizationBinding: !Ref SecurityHubMembersBinding
    Properties:
      MasterAccountId: !Ref MasterAccountId